spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/the_destination
spring.datasource.username=root
spring.datasource.password=Aayisha@#06

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080